### ISSUE TITLE
add select certain gpu's eg. 1, 2, 3

### ISSUE THREAD

**Issue by nemosminer** [nemosminer/NemosMiner-v2.0-Zpool#11]
add select certain gpu's 
eg. 1, 2, 3
or 4, 5, 6

then you can run 2x instances of NemosMiner with Alexis78 to get much improved speed for most algos on the Pascal Cards..

Next Job

**Comment by gacopl** [comment]
Also it would help if you have mixed rigs, one instance for 1070s and one for 1080s

**Comment by Citymix** [comment]
Hello ! i have problem with 6 1080ti some times in alexis78 drooping hashes,can you help how exactly select 3 gpu's ?

**Comment by nemosminer** [comment]
i'll add it in the next couple days eg. -SelGPUcc 0,1,2,3,4,5 -SelGPUewbf 0 1 2 3 4 5

**Comment by Citymix** [comment]
Thank you very much ! Waiting for the update !

**Comment by nemosminer** [comment]
done added -SelGPU 

step 1 edit: start.bat

eg: 6card rig -SelGPUEWBF '0 1 2 3 4 5" -SelGPUCC "0,1.2.3.4.5'

eg: 1 card rig -SelGPUEWBF '0" -SelGPUCC "0'

: )

**Comment by Citymix** [comment]
Thanks man thanks alot!!!I start change immediately ))
