### ISSUE TITLE
with the newest release i observe problems with lyra2v2

### ISSUE THREAD

**Issue by gacopl** [nemosminer/NemosMiner-v2.0-Zpool#18]
Hi

It happened couple times already alexis when working in lyra2v2, sometimes starts throwing illegal memory access, and it actually never dies, just stops mining throwing errors, and it continues like that until more profitable algo switches.

2x1080ti 1x1080 win10

**Comment by nemosminer** [comment]
thanks i'll do some testing

**Comment by tutulino** [comment]
same here, mixed nvidia rig ( 3 x 1080ti, 3x 1070, 1 x 1060)

**Comment by bac203** [comment]
same problem   here  gtx 1080 with ccminerAlexis78 for lyra2v2 mining

**Comment by rr32btg** [comment]
sorry for bad english.
same problem was on ASUS GTX 1080ti turbo, but when I reduce overclock(that was stable for weeks on other algos/miners) all starts work fine.

**Comment by bac203** [comment]
@rr32btg   i don't  think it's  because  of  the  overclock  cause  me when  i  restart    the miner  it work  but if it switch to it  after  mining  other  coins it just dosen't work sometimes 
depend of the mood O.o
