### ISSUE TITLE
Use Alexis78 for Keccak

### ISSUE THREAD

**Issue by MikeBuzz** [nemosminer/NemosMiner-v2.0-Zpool#23]
it seems that Alexis78 version of ccminer is quicker than the current Tpruvot and ccminer 2.2

**Comment by nemosminer** [comment]
not if you take the invalid shares into account??  gettting alot of invalid shares with Alexis78 im working on a fix with crackfoo atm

**Comment by nemosminer** [comment]
got ccminer Nanashi 1.7.6-r10 working well for Keccak faster than Tpruvot and ccminer 2.2 trying sp-mod to even faster but still getting a few invalid shares ... Alexis78 and Klaust and faster but have to many invalid shares.....
