### ISSUE TITLE
GPU #0 waiting for data

### ISSUE THREAD

**Issue by DrRobotto** [nemosminer/NemosMiner-v2.0-Zpool#24]
Hi Nemo,

I tried to run your miner on a 8 * 1060 3GB rig and on several algorithms I get the above error.
Any solutions or did I miss some point when installing your software?

Regards

**Comment by nemosminer** [comment]
Have you increased Virtual Memory 32gb-64gb is optimal

it should run great...... i have a 1060x5 rig 3gb models running atm.......

If you have Windows 7, please update PowerShell:
https://www.microsoft.com/en-us/download/details.aspx?id=50395
CCMiner may need 'MSVCR120.dll' if you don't already have it:
https://www.microsoft.com/en-gb/download/details.aspx?id=40784
CCMiner may need 'VCRUNTIME140.DLL' if you don't already have it:
https://www.microsoft.com/en-us/download/details.aspx?id=48145
running multiple cards its recommend to increase Virtual Memory 32gb-64gb is optimal

**Comment by DrRobotto** [comment]
I installed all of these files and the virtual memory is set to 64GB as well. I noticed that it happens to groestl and sometimes to neoscrypt and lyra2re2, but it is not always the case. Very strange
