### ISSUE TITLE
sometime no miner run 

### ISSUE THREAD

**Issue by bumppy** [nemosminer/NemosMiner-v2.0-Zpool#26]
hi nemo
sometime there are no miner run... i wait for next interval that i setting but it's not have next miner run again.. i must close  and re run start again...
![image](https://user-images.githubusercontent.com/30653122/28866966-ccbfcfea-779e-11e7-96ce-5fd1890eddd8.png)

**Comment by frankiereg** [comment]
Hi nemo 
My miner wI'll say out of memory  when mining lyra2re2 (alexis78) also  I've tested it and on quite a few occasions  the miner will mine to the (donate 5) address, problem with that is I've seen it mine to that address for over an hour and it only stopped cause I shut down the miner, I've put zero by donate and it still mines to that address at some point, care to explain/help

**Comment by frankiereg** [comment]
As seen in the screen, 2 different days and both is where the donation is set to 0, I've gone as far as to remove the donate string from the bat yet it still ends up miming to another address the address in question 1QGADhdMRpp***********K5R81TE (the stars is to quicken up my post) I'm not complaining about the donation, I think it's fair for the maker to get something back but my issue is with how long it mine to that address and the fact I read it would only be 5 mins per day (donation) also why when you turn the option of donation to 0 it still mines to that address.

**Comment by frankiereg** [comment]
As seen in the screen, 2 different days and both is where the donation is set to 0, I've gone as far as to remove the donate string from the bat yet it still ends up miming to another address the address in question 1QGADhdMRpp***********K5R81TE (the stars is to quicken up my post) I'm not complaining about the donation, I think it's fair for the maker to get something back but my issue is with how long it mine to that address and the fact I read it would only be 5 mins per day (donation) also why when you turn the option of donation to 0 it still mines to that address.

**Comment by nemosminer** [comment]
not sure what you what me to Explain??
what is you image showing i can't see anything wrong??
setting donation to 0 disables the donation it should not run at all...
