### ISSUE TITLE
Why average btc/day function, showing at the bottom disabled ?

### ISSUE THREAD

**Issue by Nebiforever** [nemosminer/NemosMiner-v2.0-Zpool#29]
is there anyway to enable the live income information section at the bottom of the screen like mmp ?

**Comment by Nebiforever** [comment]
i just saw this question was asked here before and those topics had been closed without answer. 

You just copy and modify multipoolminer rename it to nemosminer. Why did you remove average btc/day function, showing at the bottom ? 

Multipoolminer already has that function implemented and it's very usefull. 

i' am asking because i ran nemosminer for 3 days nonstop, i always saw nemosminer mining algos says mining over 0,0050 BTC/day (some algos peak up to 0,01 BTC/Day for some periods). but at the end of the days zpool gave me average of 0,0030-0,0035 BTC (per day). Dont tell me about difficulty or some other things because i had alotof free time and have alotof time to watch the rig my self. i' m talking about what i saw from nemosminer "Speed (BTC/Day)" section. And all of my miners are tweaked and stable, i even removed some unstable miners.

my interval is set to 300 and i dont think it's too short or long for profit switching and cause me to lose around ~ %30 - 40. 

Because if nemosminer profit switching results around  ~%30 - 40 lower than what it says it's mining, it doesnt worth it. or something else is going behind the scenes ? shall i look suspicious ?

**Comment by nemosminer** [comment]
it doesn't help profit or hashing so i don't see the point

**Comment by Nebiforever** [comment]
helps having average profit of what you mining and also helps comparing it to what pools says you mined ?
it doesnt have to be super accurate but it gives you an idea to what to expect.

**Comment by Nebiforever** [comment]
it is correct that it doesnt help profit or hashing but it eighter doesnt have any harm ?

it's only a usefull function and works good if you know how to use it. i just dont see why you keep ignoring questions about this and close the topics without any explanation ? (and other questions i asked)

really interesting, i'll be searching this one and will speak out loud dont worry ;) 

have fun

**Comment by nemosminer** [comment]
btc/ghs is all i need

**Comment by Nebiforever** [comment]
Yea it's all nemosminer(multipoolminer) need to decide which algo to switch. 

but "average profit" function is all neede by "everyone else using this script" to have an idea what to expect from mining. 

i know you understand exactly what i'm trying to say but you just dont want to understand ^^

**Comment by nemosminer** [comment]
ive been mining for years i know what to expect

**Comment by nemosminer** [comment]
i understand but im not changing it sorry

**Comment by Nebiforever** [comment]
yeh, that makes me look suspicious to your script. 

i smell non declared fee 🔢

**Comment by nemosminer** [comment]
ok smell what ever you want...

**Comment by nemosminer** [comment]
is there anyway to enable the live income information section at the bottom of the screen like mmp ?

yes there is: 
add the code Yourself..  As i don't like it.. id much Rather just BTC/per day
 it was Originally in NemosMiner at the Start....
If you really want it that bad i can make a new branch and add it for you?

**Comment by Nebiforever** [comment]
You can always make it optional for who wants to use it.

And i'd love to have that code. 

thanks

**Comment by Nebiforever** [comment]
i' m talking about this section btw, to be more clear to understand

![222](https://user-images.githubusercontent.com/30752781/29233951-a4bf24b8-7efc-11e7-9f77-c72564619b59.JPG)

**Comment by nemosminer** [comment]
ii'll add it to next release 2.2
