### ISSUE TITLE
question !

### ISSUE THREAD

**Issue by danik-guitar** [nemosminer/NemosMiner-v2.0-Zpool#30]
How does it calculate profitability ?

Why does it take courses from a cryptorator ? 

When are you doing new version? =))

**Comment by nemosminer** [comment]
How does it calculate profitability ? API

Why does it take courses from a cryptorator ? not sure i was wondering about that to, as sometime's it has error regarding cryptorator.. i'll look into it it may be for current btc price...

When are you doing new version? =)) working on it now.. im very busy with work and also sick atm so no ETA atm properly be released with a week.. adding select certain gpu's and USD per day... plus some small changes to skunk and Keccak Miners

**Comment by nemosminer** [comment]
Why does it take courses from a cryptorator ?  i does not now !  i deleted it

**Comment by nemosminer** [comment]
danik-guitar see you forked and have youtubevideo in Russian : )

**Comment by danik-guitar** [comment]
yes. i am tricky =))

**Comment by nemosminer** [comment]
its alg

**Comment by nemosminer** [comment]
https://www.youtube.com/watch?v=UCTkw7pJruA
