### ISSUE TITLE
Cannot add other Alg's

### ISSUE THREAD

**Issue by Hypheonix** [nemosminer/NemosMiner-v2.0-Zpool#32]
Having an issue when adding alg's to the bat file, it's not showing for benchmarking or mining. Any thoughts?

http://imgur.com/a/I2gAB

**Comment by nemosminer** [comment]
wheres the Issue that image is of a half complete benchmark...  did it just stop half way through?? i have never had that happen.....

**Comment by Hypheonix** [comment]
Yeah I finshed the benchmark, but I had other Algs that I added to my bat file that were not include in the benchmarking.

**Comment by jimmykl** [comment]
So then when the miner is run it will benchmark those new algos… which it is doing in your screenshot… Once it has benchmarked all the algos from the bat file it will begin auto-switching. No issue here?

**Comment by nemosminer** [comment]
both those Algos are not profitable with Nvida atm but you if you want to enable them: 
you will have to go into Miners Folder:

edit which ccminer.ps1 you want to run for those algos and remove the # from in front of the algo 
eg   x11 and decred Enabled

       "decred" = "" #Decred
    #"equihash" = "" #Equihash
    #"ethash" = "" #Ethash
    #"groestl" = "" #Groestl
    "hmq1725" = "" #hmq1725
    #"keccak" = "" #Keccak
    "lbry" = "" #Lbry
    #"lyra2v2" = "" #Lyra2RE2
    #"lyra2z" = "" #Lyra2z
    #"myr-gr" = "" #MyriadGroestl
    "neoscrypt" = "" #NeoScrypt
    #"nist5" = "" #Nist5
    #"pascal" = "" #Pascal
    #"qubit" = "" #Qubit
    #"scrypt" = "" #Scrypt
    #"sia" = "" #Sia
    "sib" = "" #Sib
    #"skein" = "" #Skein
    "timetravel" = "" #Timetravel
    "x11" = "" #X11
    #"veltor" = "" #Veltor:

**Comment by nemosminer** [comment]
sorted
