### ISSUE TITLE
myr-gr

### ISSUE THREAD

**Issue by danik-guitar** [nemosminer/NemosMiner-v2.0-Zpool#34]
algorithm 'myr-gr'  dont work .
In megaminer tutulino 'myr-gr' works
![qip shot - screen 2017 08 15 12-54-13](https://user-images.githubusercontent.com/30734827/29311051-e8557f74-81b8-11e7-99d3-6391d20bd4c8.jpg)
![qip shot - screen 2017 08 15 12-51-51](https://user-images.githubusercontent.com/30734827/29311052-e8565516-81b8-11e7-9229-c89d29430e53.jpg)

**Comment by nemosminer** [comment]
works for me...

**Comment by nemosminer** [comment]
![image](https://user-images.githubusercontent.com/25545633/29329614-8d8dac46-824a-11e7-9834-165d50210cb9.png)
