### ISSUE TITLE
Continue mining if zpool api not responded (No Pool)

### ISSUE THREAD

**Issue by papampi** [nemosminer/NemosMiner-v2.0-Zpool#35]
Zpool api gives so many timeouts.
Its best if Nemos continue mining with the last profit files then check again in sync interval for newer benefits.
I think Nemos should 1st download profit file from zpool api, make it ready to use , then replace them with old ones, so powershell always have profit files to use.

**Comment by papampi** [comment]
Some one mentioned in another miner they solved timeouts by adding -timeoutsec 5 to api request                             
from :
    $Zpool_Request = Invoke-WebRequest "http://www.zpool.ca/api/status" -UseBasicParsing | ConvertFrom-Json
to :
$Zpool_Request = Invoke-WebRequest "http://www.zpool.ca/api/status" -UseBasicParsing -timeoutsec 5 | ConvertFrom-Json

**Comment by papampi** [comment]
tested timeoutsec, not working as I thought

**Comment by UselessGuru** [comment]
Could be resolved by caching the last web request as described here:
 #[https://github.com/aaronsace/MultiPoolMiner/issues/280](url)
