### ISSUE TITLE
Only 2 miner threads started?

### ISSUE THREAD

**Issue by batuperm4t4** [nemosminer/NemosMiner-v2.0-Zpool#49]
Hallo,

I'm mining with 6 GPU  of MSI GTX 1060 and everytime I start mining only 2 GPU is working GPU 0 and GPU1. All my GPU is detected in windows and fine, only when I start mining with NemosMiner it only run 2 GPU.

do you have solutions Aaron or anyone? Thanks :)

**Comment by jimmykl** [comment]
Have you edited start.bat to include 6 GPUs? e.g.
`-SelGPUEWBF` '0 1 2 3 4 5' -SelGPUCC '0,1,2,3,4,5'`

**Comment by batuperm4t4** [comment]
Yes! it's working now :)
Thanks!

**Comment by jimmykl** [comment]
Cool! Don't forget to close the issue :)

**Comment by batuperm4t4** [comment]
I run 6 of GPU but take too long time for zpool to accept the job, and then I run 4 of GPU and still too slow for job accepted, but when I try to run only 3 of GPU the job accepted and run normally.

do you think it because my internet connection or the NemosMiner script?

Thanks

**Comment by batuperm4t4** [comment]
nice NemosMiner :)
