### ISSUE TITLE
Lbry

### ISSUE THREAD

**Issue by nemosminer** [nemosminer/NemosMiner-v2.0-Zpool#5]
add Lbry algo

Find fastest Ccminer that works well with 6+cards 
make sure that ccminer does not contain a sp-mod DEV FEE : )

Next job

**Comment by nemosminer** [comment]
added lbry & veltor test both tp and kt for best results and disable slower

**Comment by BitForesters** [comment]
KlausT fails on both LBRY and Veltor on my rigs. 6x 1070s on each rig.

**Comment by nemosminer** [comment]
lbry and veltor done
