### ISSUE TITLE
Hashrate hmq1725

### ISSUE THREAD

**Issue by DrRobotto** [nemosminer/NemosMiner-v2.0-Zpool#6]
When I mine hmq1725, the miner shows about 4MH/s but zpool shows only 100kH/s.
This should not be the case?!? Or am I missing some point here?

**Comment by nemosminer** [comment]
you r  missing some point here? 
* approximate from the last 5 minutes submitted shares 
it changes algo so it takes a few minutes to show full hashrate it not instant

**Comment by DrRobotto** [comment]
Hm, I mined over 40 minutes and it did not went higher than 100kH/s
